version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: janedoe
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: walaser
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./laser_tag_admin/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    command: ["poetry", "run", "python", "bot/telegram_bot.py"]
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PYTHONPATH: /app
