version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=janedoe
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=walaser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}

volumes:
  postgres_data:
