# Generated by Django 5.1.3 on 2024-11-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество записанных игроков'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='ID в Telegram')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра')),
            ],
        ),
    ]
