# Generated by Django 5.1.3 on 2024-11-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_players_count_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
