# Generated by Django 5.1.3 on 2024-11-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_status_delete_player'),
        ('users', '0003_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Количество гостей')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация на игру',
                'verbose_name_plural': 'Регистрации на игры',
                'unique_together': {('user', 'game')},
            },
        ),
    ]
