# Generated by Django 5.1.3 on 2024-11-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_count',
        ),
    ]
